import Head from "next/head";
import { Router, } from "next/router";
import SideNavbar from "../components/SideNavbar";
export default function Home() {
  return (
    <div className="bg-blue-800">
      <Head>
        <title>Dashboard App</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/alterra.ico" />
      </Head>
      
      <SideNavbar />


    </div>
  );
}
